openapi: 3.0.3
info:
    title: Chatbook Microservices
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for chatbook-microservices
paths:
    /api/chat/v1/conversation:
        post:
            tags:
                - chat
            summary: addConversation chat
            operationId: chat#addConversation
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddConversationRequestBody'
                        example:
                            participants:
                                - email: Et sunt earum.
                                  firstName: Enim vel sapiente.
                                  id: Quia vero illum eos quidem sapiente.
                                  lastName: Molestiae similique omnis voluptate pariatur non.
                                - email: Et sunt earum.
                                  firstName: Enim vel sapiente.
                                  id: Quia vero illum eos quidem sapiente.
                                  lastName: Molestiae similique omnis voluptate pariatur non.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OperationStatusResponse'
                            example:
                                message: Cum soluta possimus accusamus similique quibusdam.
    /api/chat/v1/conversations:
        get:
            tags:
                - chat
            summary: getConversationsList chat
            operationId: chat#getConversationsList
            parameters:
                - name: limit
                  in: query
                  description: Messages count
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: Messages count
                    default: 100
                    example: 7707728214343897156
                    format: int64
                  example: 5067025365231145645
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ConversationsListResponse'
                            example:
                                resources:
                                    - ID: Ut sed.
                                      lastMessageContent: Est consequatur voluptatem quas libero.
                                      lastMessageDeliveredAt: In tempore consequatur nemo laboriosam optio at.
                                      lastMessageSenderID: Earum ab est ipsa sint quasi.
                                      otherParticipantID: Facere molestiae cumque quia.
                                    - ID: Ut sed.
                                      lastMessageContent: Est consequatur voluptatem quas libero.
                                      lastMessageDeliveredAt: In tempore consequatur nemo laboriosam optio at.
                                      lastMessageSenderID: Earum ab est ipsa sint quasi.
                                      otherParticipantID: Facere molestiae cumque quia.
                                total: 2652986931880041573
    /api/chat/v1/conversations/{ID}:
        get:
            tags:
                - chat
            summary: searchInConversation chat
            operationId: chat#searchInConversation
            parameters:
                - name: limit
                  in: query
                  description: Messages count
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: Messages count
                    default: 200
                    example: 4225528609426357256
                    format: int64
                  example: 776138541452030313
                - name: searchInput
                  in: query
                  description: Input
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Input
                    default: "200"
                    example: qyl
                    minLength: 5
                  example: 9wc
                - name: ID
                  in: path
                  description: Conversation ID
                  required: true
                  schema:
                    type: string
                    description: Conversation ID
                    example: A aut.
                  example: Quas nihil.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ChatHistoryResponse'
                            example:
                                count: 7212916668972977683
                                id: Eos rerum dolor.
                                messages:
                                    - content: Et velit illo fugit.
                                      senderID: Quo quia et.
                                      timestamp: Nisi eos vel atque necessitatibus eum.
                                    - content: Et velit illo fugit.
                                      senderID: Quo quia et.
                                      timestamp: Nisi eos vel atque necessitatibus eum.
                                    - content: Et velit illo fugit.
                                      senderID: Quo quia et.
                                      timestamp: Nisi eos vel atque necessitatibus eum.
                                    - content: Et velit illo fugit.
                                      senderID: Quo quia et.
                                      timestamp: Nisi eos vel atque necessitatibus eum.
    /api/chat/v1/conversations/{ID}/history:
        get:
            tags:
                - chat
            summary: getConversationHistory chat
            operationId: chat#getConversationHistory
            parameters:
                - name: limit
                  in: query
                  description: Messages count
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: Messages count
                    default: 200
                    example: 4770253716701939495
                    format: int64
                  example: 4468727849277162674
                - name: beforeTimestamp
                  in: query
                  description: Before timestamp
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Before timestamp
                    default: "2023-06-06 00:00:00.323108"
                    example: Dignissimos officiis harum iste delectus voluptatem corporis.
                  example: Provident non dolores consequatur non nulla aperiam.
                - name: ID
                  in: path
                  description: Conversation ID
                  required: true
                  schema:
                    type: string
                    description: Conversation ID
                    example: Asperiores corporis ut sit.
                  example: Ab debitis earum.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ChatHistoryResponse'
                            example:
                                count: 6041346671071199815
                                id: Magni officia maxime aut unde libero.
                                messages:
                                    - content: Et velit illo fugit.
                                      senderID: Quo quia et.
                                      timestamp: Nisi eos vel atque necessitatibus eum.
                                    - content: Et velit illo fugit.
                                      senderID: Quo quia et.
                                      timestamp: Nisi eos vel atque necessitatibus eum.
                                    - content: Et velit illo fugit.
                                      senderID: Quo quia et.
                                      timestamp: Nisi eos vel atque necessitatibus eum.
                                    - content: Et velit illo fugit.
                                      senderID: Quo quia et.
                                      timestamp: Nisi eos vel atque necessitatibus eum.
    /api/user-management/v1/auth/login:
        post:
            tags:
                - auth
            summary: login auth
            operationId: auth#login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestBody'
                        example:
                            email: Quasi quas.
                            password: Sint quia molestias aut dolores soluta.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponse'
                            example:
                                email: Recusandae libero omnis commodi qui quis et.
                                id: Eum ullam eveniet temporibus quis dolore mollitia.
                                refresh_token: Rerum qui.
                                role: Laboriosam tempore atque mollitia ut.
                                token: Modi officia ipsum consequatur quas velit et.
                "404":
                    description: 'WrongCredentials: Email and/or password don''t match'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/user-management/v1/auth/refresh-token:
        post:
            tags:
                - auth
            summary: refreshToken auth
            operationId: auth#refreshToken
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RefreshTokenRequestBody'
                        example:
                            email: Molestiae sit enim non ratione maxime molestiae.
                            refreshToken: Dolorum rerum.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponse'
                            example:
                                email: Dolores quibusdam.
                                id: Possimus ad.
                                refresh_token: Ut ut.
                                role: Optio a.
                                token: Labore tempora.
    /api/user-management/v1/info:
        get:
            tags:
                - info
            summary: getInfo info
            operationId: info#getInfo
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OperationStatusResponse'
                            example:
                                message: Distinctio sunt necessitatibus.
    /api/user-management/v1/users/friend/{id}:
        post:
            tags:
                - user
            summary: addFriend user
            operationId: user#addFriend
            parameters:
                - name: id
                  in: path
                  description: User ID to add
                  required: true
                  schema:
                    type: string
                    description: User ID to add
                    example: Reiciendis quis quia qui rerum nulla.
                  example: Eos dolor pariatur asperiores commodi aperiam.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OperationStatusResponse'
                            example:
                                message: Iste omnis exercitationem.
    /api/user-management/v1/users/friends/{id}:
        delete:
            tags:
                - user
            summary: removeFriend user
            operationId: user#removeFriend
            parameters:
                - name: id
                  in: path
                  description: User ID to delete
                  required: true
                  schema:
                    type: string
                    description: User ID to delete
                    example: Sunt ipsam quis et repellat.
                  example: Laudantium soluta.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OperationStatusResponse'
                            example:
                                message: Esse adipisci hic assumenda.
    /api/user-management/v1/users/profile:
        get:
            tags:
                - user
            summary: getProfile user
            operationId: user#getProfile
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UserProfileResponse'
                            example:
                                email: Labore aut vel.
                                firstName: Eligendi reiciendis fuga.
                                friendsList:
                                    - email: Asperiores illum accusantium nam ipsa.
                                      firstName: Natus animi aperiam veniam enim.
                                      id: Qui sequi voluptates.
                                      lastName: Ad voluptatem dolor quae.
                                    - email: Asperiores illum accusantium nam ipsa.
                                      firstName: Natus animi aperiam veniam enim.
                                      id: Qui sequi voluptates.
                                      lastName: Ad voluptatem dolor quae.
                                id: Deleniti aut.
                                lastName: Non ut voluptas aut.
        put:
            tags:
                - user
            summary: updateProfileNames user
            operationId: user#updateProfileNames
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateProfileNamesRequestBody'
                        example:
                            firstName: Voluptates blanditiis eum ex nam dolorem fugit.
                            lastName: Id velit sint fuga ut dolores quia.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OperationStatusResponse'
                            example:
                                message: Velit enim modi consequatur.
    /api/user-management/v1/users/register:
        post:
            tags:
                - user
            summary: register user
            operationId: user#register
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RegisterRequestBody'
                        example:
                            confirmedPassword: Impedit nisi assumenda ipsum adipisci.
                            email: Aliquam modi deleniti earum ea repellendus.
                            firstName: Veniam eos rerum quas et et.
                            lastName: Occaecati minima amet architecto sint.
                            password: Nihil excepturi dolore eveniet ratione.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OperationStatusResponse'
                            example:
                                message: Qui voluptates nostrum iure incidunt dolorem.
                "409":
                    description: 'UnmatchingPassowrds: Provided passwords are not the same'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        AddConversationRequestBody:
            type: object
            properties:
                participants:
                    type: array
                    items:
                        $ref: '#/components/schemas/Friend'
                    description: Participants
                    example:
                        - email: Et sunt earum.
                          firstName: Enim vel sapiente.
                          id: Quia vero illum eos quidem sapiente.
                          lastName: Molestiae similique omnis voluptate pariatur non.
                        - email: Et sunt earum.
                          firstName: Enim vel sapiente.
                          id: Quia vero illum eos quidem sapiente.
                          lastName: Molestiae similique omnis voluptate pariatur non.
            example:
                participants:
                    - email: Et sunt earum.
                      firstName: Enim vel sapiente.
                      id: Quia vero illum eos quidem sapiente.
                      lastName: Molestiae similique omnis voluptate pariatur non.
                    - email: Et sunt earum.
                      firstName: Enim vel sapiente.
                      id: Quia vero illum eos quidem sapiente.
                      lastName: Molestiae similique omnis voluptate pariatur non.
                    - email: Et sunt earum.
                      firstName: Enim vel sapiente.
                      id: Quia vero illum eos quidem sapiente.
                      lastName: Molestiae similique omnis voluptate pariatur non.
            required:
                - participants
        ChatHistoryResponse:
            type: object
            properties:
                count:
                    type: integer
                    description: Messages Count
                    example: 1017924483204450261
                    format: int64
                id:
                    type: string
                    description: Chatroom ID
                    example: Illum temporibus beatae.
                messages:
                    type: array
                    items:
                        $ref: '#/components/schemas/ConversationMessage'
                    description: Chat history
                    example:
                        - content: Et velit illo fugit.
                          senderID: Quo quia et.
                          timestamp: Nisi eos vel atque necessitatibus eum.
                        - content: Et velit illo fugit.
                          senderID: Quo quia et.
                          timestamp: Nisi eos vel atque necessitatibus eum.
                        - content: Et velit illo fugit.
                          senderID: Quo quia et.
                          timestamp: Nisi eos vel atque necessitatibus eum.
                        - content: Et velit illo fugit.
                          senderID: Quo quia et.
                          timestamp: Nisi eos vel atque necessitatibus eum.
            example:
                count: 3607886237262746381
                id: Et est asperiores.
                messages:
                    - content: Et velit illo fugit.
                      senderID: Quo quia et.
                      timestamp: Nisi eos vel atque necessitatibus eum.
                    - content: Et velit illo fugit.
                      senderID: Quo quia et.
                      timestamp: Nisi eos vel atque necessitatibus eum.
                    - content: Et velit illo fugit.
                      senderID: Quo quia et.
                      timestamp: Nisi eos vel atque necessitatibus eum.
                    - content: Et velit illo fugit.
                      senderID: Quo quia et.
                      timestamp: Nisi eos vel atque necessitatibus eum.
            required:
                - id
                - count
                - messages
        Conversation:
            type: object
            properties:
                ID:
                    type: string
                    description: Conversation ID
                    example: Architecto nulla molestiae omnis doloremque rerum.
                lastMessageContent:
                    type: string
                    description: Last message
                    example: Facilis et praesentium.
                lastMessageDeliveredAt:
                    type: string
                    description: TS for delivered time
                    example: Fuga adipisci blanditiis sed voluptatem sint veniam.
                lastMessageSenderID:
                    type: string
                    description: Sender ID
                    example: Voluptates incidunt.
                otherParticipantID:
                    type: string
                    description: TS for delivered time
                    example: Consequatur aut id sit consequatur quis autem.
            example:
                ID: Placeat vitae error assumenda libero.
                lastMessageContent: Culpa quam enim et vero architecto laboriosam.
                lastMessageDeliveredAt: Animi vero eum.
                lastMessageSenderID: Nulla harum voluptatem.
                otherParticipantID: Voluptatum optio nemo velit fugiat.
            required:
                - ID
                - lastMessageSenderID
                - lastMessageContent
                - lastMessageDeliveredAt
                - otherParticipantID
        ConversationMessage:
            type: object
            properties:
                content:
                    type: string
                    description: Message Content
                    example: Cum rerum dolorem quaerat vel.
                senderID:
                    type: string
                    description: Sender ID
                    example: Voluptate dolores alias saepe fugiat.
                timestamp:
                    type: string
                    description: Timestamp of the message
                    example: Suscipit et.
            example:
                content: Cum aut mollitia totam fuga.
                senderID: Et fuga repellendus.
                timestamp: In earum hic voluptas ut cupiditate.
            required:
                - timestamp
                - senderID
                - content
        ConversationsListResponse:
            type: object
            properties:
                resources:
                    type: array
                    items:
                        $ref: '#/components/schemas/Conversation'
                    description: Chat history
                    example:
                        - ID: Ut sed.
                          lastMessageContent: Est consequatur voluptatem quas libero.
                          lastMessageDeliveredAt: In tempore consequatur nemo laboriosam optio at.
                          lastMessageSenderID: Earum ab est ipsa sint quasi.
                          otherParticipantID: Facere molestiae cumque quia.
                        - ID: Ut sed.
                          lastMessageContent: Est consequatur voluptatem quas libero.
                          lastMessageDeliveredAt: In tempore consequatur nemo laboriosam optio at.
                          lastMessageSenderID: Earum ab est ipsa sint quasi.
                          otherParticipantID: Facere molestiae cumque quia.
                        - ID: Ut sed.
                          lastMessageContent: Est consequatur voluptatem quas libero.
                          lastMessageDeliveredAt: In tempore consequatur nemo laboriosam optio at.
                          lastMessageSenderID: Earum ab est ipsa sint quasi.
                          otherParticipantID: Facere molestiae cumque quia.
                        - ID: Ut sed.
                          lastMessageContent: Est consequatur voluptatem quas libero.
                          lastMessageDeliveredAt: In tempore consequatur nemo laboriosam optio at.
                          lastMessageSenderID: Earum ab est ipsa sint quasi.
                          otherParticipantID: Facere molestiae cumque quia.
                total:
                    type: integer
                    description: Messages Count
                    example: 4453666120779163880
                    format: int64
            example:
                resources:
                    - ID: Ut sed.
                      lastMessageContent: Est consequatur voluptatem quas libero.
                      lastMessageDeliveredAt: In tempore consequatur nemo laboriosam optio at.
                      lastMessageSenderID: Earum ab est ipsa sint quasi.
                      otherParticipantID: Facere molestiae cumque quia.
                    - ID: Ut sed.
                      lastMessageContent: Est consequatur voluptatem quas libero.
                      lastMessageDeliveredAt: In tempore consequatur nemo laboriosam optio at.
                      lastMessageSenderID: Earum ab est ipsa sint quasi.
                      otherParticipantID: Facere molestiae cumque quia.
                total: 7060662816383704251
            required:
                - total
                - resources
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        Friend:
            type: object
            properties:
                email:
                    type: string
                    description: Email
                    example: Pariatur iusto explicabo fuga.
                firstName:
                    type: string
                    description: First name
                    example: Voluptatum totam aut nam et.
                id:
                    type: string
                    description: User ID
                    example: Nisi reprehenderit.
                lastName:
                    type: string
                    description: Last name
                    example: Ut quod sapiente.
            example:
                email: Quis eaque fuga adipisci voluptate.
                firstName: Unde perspiciatis perspiciatis ipsa ipsa quasi tempore.
                id: Porro autem doloribus accusantium architecto iusto.
                lastName: Nisi adipisci qui beatae voluptatem.
            required:
                - id
                - email
                - firstName
                - lastName
        LoginRequestBody:
            type: object
            properties:
                email:
                    type: string
                    description: User email
                    example: Neque aut qui.
                password:
                    type: string
                    description: User password
                    example: Cum perspiciatis rerum eius.
            example:
                email: Non nesciunt sit molestias et.
                password: Nostrum aliquid.
            required:
                - email
                - password
        LoginResponse:
            type: object
            properties:
                email:
                    type: string
                    description: User's email
                    example: Dolores omnis exercitationem ea nam quaerat.
                id:
                    type: string
                    description: User account's ID
                    example: Perferendis fuga qui quidem exercitationem.
                refresh_token:
                    type: string
                    description: Refresh token
                    example: Repellendus magnam qui.
                role:
                    type: string
                    description: User's role
                    example: Eligendi neque.
                token:
                    type: string
                    description: JWT Token
                    example: Sed rerum aliquid qui quisquam asperiores fugiat.
            example:
                email: Cupiditate fuga provident velit.
                id: Est animi numquam minus vitae qui.
                refresh_token: Debitis itaque.
                role: Quia modi doloremque.
                token: Ab et eaque nemo dignissimos.
            required:
                - email
                - token
                - refresh_token
                - role
        OperationStatusResponse:
            type: object
            properties:
                message:
                    type: string
                    description: Operation status
                    example: Fugit alias voluptatum.
            example:
                message: Aut adipisci accusamus dolor vero ab quis.
            required:
                - message
        RefreshTokenRequestBody:
            type: object
            properties:
                email:
                    type: string
                    description: User email
                    example: Quae nulla praesentium magnam et suscipit veniam.
                refreshToken:
                    type: string
                    description: Refresh token
                    example: Ipsa labore.
            example:
                email: Maxime quibusdam.
                refreshToken: Qui animi qui excepturi.
            required:
                - email
                - refreshToken
        RegisterRequestBody:
            type: object
            properties:
                confirmedPassword:
                    type: string
                    description: Confirmed password of the user
                    example: Porro est.
                email:
                    type: string
                    description: User email
                    example: Qui excepturi illum sunt numquam quia.
                firstName:
                    type: string
                    description: User first name
                    example: At reprehenderit recusandae quod perspiciatis.
                lastName:
                    type: string
                    description: User last name
                    example: Quibusdam minima est ut quia eos omnis.
                password:
                    type: string
                    description: User password
                    example: Maxime aut nobis.
            example:
                confirmedPassword: Culpa provident saepe.
                email: Error eligendi optio quaerat corrupti.
                firstName: Repudiandae modi accusamus dolore suscipit.
                lastName: Dignissimos distinctio.
                password: Cupiditate repellendus sint accusamus sed unde.
            required:
                - email
                - password
                - confirmedPassword
                - firstName
                - lastName
        UpdateProfileNamesRequestBody:
            type: object
            properties:
                firstName:
                    type: string
                    description: Updated user first name
                    example: Sint aut suscipit et a.
                lastName:
                    type: string
                    description: Updated user last name
                    example: Id est voluptatem in eius.
            example:
                firstName: Voluptates culpa occaecati rem dolorem quos dolores.
                lastName: Nemo eum quia quo aut facere excepturi.
            required:
                - firstName
                - lastName
        UserProfileResponse:
            type: object
            properties:
                email:
                    type: string
                    description: Email
                    example: Officia sit cumque quia.
                firstName:
                    type: string
                    description: First name
                    example: Aut aut eum maxime.
                friendsList:
                    type: array
                    items:
                        $ref: '#/components/schemas/Friend'
                    description: Friendslist
                    example:
                        - email: Asperiores illum accusantium nam ipsa.
                          firstName: Natus animi aperiam veniam enim.
                          id: Qui sequi voluptates.
                          lastName: Ad voluptatem dolor quae.
                        - email: Asperiores illum accusantium nam ipsa.
                          firstName: Natus animi aperiam veniam enim.
                          id: Qui sequi voluptates.
                          lastName: Ad voluptatem dolor quae.
                id:
                    type: string
                    description: User ID
                    example: Accusamus mollitia excepturi expedita tempora pariatur.
                lastName:
                    type: string
                    description: Last name
                    example: Dolorum blanditiis.
            example:
                email: Et aperiam nam voluptates est.
                firstName: Numquam amet ipsum nobis enim ut.
                friendsList:
                    - email: Asperiores illum accusantium nam ipsa.
                      firstName: Natus animi aperiam veniam enim.
                      id: Qui sequi voluptates.
                      lastName: Ad voluptatem dolor quae.
                    - email: Asperiores illum accusantium nam ipsa.
                      firstName: Natus animi aperiam veniam enim.
                      id: Qui sequi voluptates.
                      lastName: Ad voluptatem dolor quae.
                id: Repellendus molestiae voluptatem suscipit et quia.
                lastName: Sed quam veniam autem qui quibusdam.
            required:
                - id
                - email
                - firstName
                - lastName
                - friendsList
tags:
    - name: auth
      description: Authentication service is responsible for handling user data and requests
    - name: info
      description: Application info
    - name: chat
      description: User service is responsible for handling user data and requests
    - name: user
      description: User service is responsible for handling user data and requests
